inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - spec/**/*
    - config/**/*
    - bin/*
    - tmp/**/*
    - vendor/**/*
    - lib/*

# Rails

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/HasAndBelongsToMany:
  Description: 'Prefer has_many :through to has_and_belengs_to_many.'
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

# Style

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    find: detect
    inject: reduce
    collect: map
    find_all: select

Style/StructInheritance:
  Exclude:
    - app/policies/**/*