version: '3'
services:
  db:
    image: postgres:10-alpine
    build:
      context: ./services/backend/db
      dockerfile: Dockerfile
    ports:
      - "5432"
  backend:
    build:
      context: keto-backend
      args:
        UID: ${UID:-1001}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend