version: '2'
services:
  web:
    image: myapp
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    ports:
      - "3000"
    environment:
      - VIRTUAL_HOST=myapp.dev
    command: bundle exec rails s -b 0.0.0.0
  sidekiq:
    image: myapp
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    command: bundle exec sidekiq
  postgres:
    image: postgres:9.5
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgres
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local