---
- name: "restart redis {{ redis_port }}"
  service:
    name: redis_{{ redis_port }}
    state: restarted
  when: redis_as_service

- name: "restart sentinel {{ redis_sentinel_port }}"
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
  when: redis_as_service
