
test:
  adapter: postgresql
  encoding: unicode    
  template: template0
  database: (azbuker_test_db)
  pool: 5
  username: (your_local_pg_user for azbuker)
  password: (your_local_pg_user pass)
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  template: template0
  database: (azbuker_dev_db)
  pool: 5
  username: (your_local_pg_user for azbuker)
  password: (your_local_pg_user pass)
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: (azbuker_production_db)
  pool: 5
  username: (your_production_pg_user)
  password: (_postgres_user_pass)
  host: localhost