on: push
name: Test and deploy to heroku
jobs:
  build:
    name: ruby.build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: ruby.build
      uses: actions/docker/cli@master
      with:
        args: build -f Dockerfile -t ci-${{ github.sha }}:latest .
#     - name: ruby.rspec
#       uses: actions/docker/cli@master
#       with:
#         args: run ci-${{ github.sha }}:latest rspec
    - name: ruby.rubocop
      uses: actions/docker/cli@master
      with:
        args: run ci-${{ github.sha }}:latest rubocop
    - name: git.master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: heroku.login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: heroku.push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
        RAILS_ENV: production
      with:
        args: container:push web
    - name: heroku.envs
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
        MY_SECRET: ${{ secrets.MY_SECRET }}
        RAILS_ENV: production
      with:
        args: config:set RACK_ENV=$RACK_ENV MY_SECRET=$MY_SECRET
    - name: heroku.deploy
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
        MY_SECRET: ${{ secrets.MY_SECRET }}
        RAILS_ENV: production
      with:
        args: container:release web
    - name: msteams.notifier
      uses: docker://chzbrgr71/post-msteams
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
      with:
        args: Deployed!
